kind: Secret
apiVersion: v1
metadata:
  name: spark-quay-secret
  namespace: spark-datamesh-demo
  uid: 3f908a91-a8b4-49f2-a43b-d1282d46e84f
  resourceVersion: '52803716'
  creationTimestamp: '2024-05-17T19:50:26Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{".dockerconfigjson":"eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoianBhdWxyYWpfc2VfamJvc3MiLCJwYXNzd29yZCI6IlJlZGhhdDIwMjQkIiwiZW1haWwiOiJqcGF1bHJhakByZWRoYXQuY29tIiwiYXV0aCI6ImFuQmhkV3h5WVdwZmMyVmZhbUp2YzNNNlVtVmthR0YwTWpBeU5DUT0ifX19"},"kind":"Secret","metadata":{"annotations":{"kubernetes.io/dockerconfigjson":"true"},"name":"spark-quay-secret","namespace":"spark-datamesh-demo"},"type":"kubernetes.io/dockerconfigjson"}
    kubernetes.io/dockerconfigjson: 'true'
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2024-05-17T19:50:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:.dockerconfigjson': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
            'f:kubernetes.io/dockerconfigjson': {}
        'f:type': {}
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoianBhdWxyYWpfc2VfamJvc3MiLCJwYXNzd29yZCI6IlJlZGhhdDIwMjQkIiwiZW1haWwiOiJqcGF1bHJhakByZWRoYXQuY29tIiwiYXV0aCI6ImFuQmhkV3h5WVdwZmMyVmZhbUp2YzNNNlVtVmthR0YwTWpBeU5DUT0ifX19
type: kubernetes.io/dockerconfigjson
